I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 150, in script call
    call puzzle_1
  File "game/script.rpy", line 162, in script
    $ score_puzzle += 10
  File "game/script.rpy", line 162, in <module>
    $ score_puzzle += 10
NameError: name 'score_puzzle' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 150, in script call
    call puzzle_1
  File "game/script.rpy", line 162, in script
    $ score_puzzle += 10
  File "C:\Users\HP\Downloads\RENPY\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\HP\Downloads\RENPY\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 162, in <module>
    $ score_puzzle += 10
NameError: name 'score_puzzle' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
Sea Savers 1.0
Tue Dec 10 02:30:58 2024
